language: rust
env:
  global:
  - PROJECT_NAME: scHLAcount
  - RUST_BACKTRACE: full
matrix:
  fast_finish: true
  include:
  - os: osx
    rust: stable
    env: TARGET=x86_64-apple-darwin
  - os: linux
    rust: stable
    env: TARGET=x86_64-unknown-linux-gnu
install: ci/install.sh
script: ci/script.sh
before_deploy: ci/before_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: "HHeptIdhv70nFn/qmKyRj42p4GNHE2AZxTgS9TEOL/rcN1+7G5UJojydGqhGlcrCxPLHeJjccgDKEZdvLidh9wFIjNdtyGC25gK49nwRZ773fuvNcRfZjrea96D85TFvMsUv8u+JPPIY9MZb+kBmsVgMCIw14Nr7Tq0tjQiW8TilP2V4n1fobcNYdDbYMPxYue9Os+Prz7K3cMMn3qVjlm5EkZIWDNygSf1+R+WGDMpdcHCu1jC+y6OtScJeqAtnQlz+6vvPV9L3EvSqj5GTTYpfWXNz0CkHr7E8w9BAZ6Lfrm0GEJ7UNY2UXaq/Nhd5yK6HL6GqObeERmcXbUf8jZySTrI/ccbtGna2wm+1BXnItjSmjsDzzrMWABuuo6KuNE9Egy3atmGt4qmqqNpmqX2c2Gany3LHFvjhJQ2mxyTjqDJyV0dY7dCzjL0OC1/IEV4SIurg0sig3e7fSysrwwvVz3mJxW3YGhGfWtYWjEMxnwu/1FpcxYkgxeO5/p3vqVQabDuE1JeTtemr7RR4xDlkRqpZCLsIi58zv1pkgQshH0ssTWJkEK8viuYpSCrp7NniBD/xufnHnBCEhOF0glV4pAFEq9gBlnf5nl3QUR9Qh9H1Yjrin4muBCo/SpobanDypqtt4P3htHgBfsfVALK+ddqReaFs8gnu2DsNJmI="
  file: deployment/${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: 10XGenomics/scHLAcount
    branch: master
    tags: true
